services:
  docs:
    image: lm_tracker_local_docs
    container_name: lm_tracker_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./lm_tracker:/app/lm_tracker:z
    ports:
      - '9000:9000'
    command: /start-docs
